version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/meteor-chat-app
hooks:
  AfterInstall:
    - location : scripts/npm-install.sh
      timeout : 360
      runas: ubuntu
    - location: scripts/meteor-run.sh
      timeout : 360 
      runas: ubuntu